shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.3
cpus: 2
memory: 8192

containers:
  - name: "app"
    image: "ghcr.io/tanyav2/simple-container-private:latest@sha256:d699a189a47c0cabfe42f89f41bc99e4d7c43ba47c4efca8b3ec5df4a991510d"
    env:
      - APP_NAME=tinfoil-test-app"
      - LOG_LEVEL=debug"
      - MAX_TOKENS=100"
    secrets:
      - TINFOIL_API_KEY

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
    - /chat
