shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.3
cpus: 2
memory: 8192

containers:
  - name: "app"
    image: "ubuntu@sha256:a4453623f2f8319cfff65c43da9be80fe83b1a7ce689579b475867d69495b782"
    env:
      - APP_NAME=tinfoil-test-app
      - LOG_LEVEL=debug

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
